name: Claude Code Dispatch

on:
  repository_dispatch:
    types: [claude-dispatch]

jobs:
  claude-dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write 
      issues: write
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}